### ISSUE TITLE
parser crash resulting in note corruption while editing

### ISSUE THREAD

**Issue by obilodeau** [tomboy-notes/tomdroid#1]
This is a bug opened mostly for myself so I can reproduce and give better explanations later. Right now I'm in a rush release mode so I have no time to track this.

Stack trace:
10-17 05:04:46.815: V/NoteContentBuilder(539): parsing note Stuff to see
10-17 05:04:46.815: W/System.err(539): org.apache.harmony.xml.ExpatParser$ParseException: At line 3, column 48: not well-formed (invalid token)
10-17 05:04:46.855: W/System.err(539):  at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:499)
10-17 05:04:46.855: W/System.err(539):  at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
10-17 05:04:46.855: W/System.err(539):  at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
10-17 05:04:46.855: W/System.err(539):  at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
10-17 05:04:46.855: W/System.err(539):  at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
10-17 05:04:46.865: W/System.err(539):  at org.tomdroid.util.NoteContentBuilder$1.run(NoteContentBuilder.java:103)
10-17 05:04:46.865: W/System.err(539):  at java.lang.Thread.run(Thread.java:856)
10-17 05:04:46.865: E/NoteContentBuilder(539): There was an error parsing the note <note-content>
10-17 05:04:46.865: E/NoteContentBuilder(539): Pour Stéph:
10-17 05:04:46.865: E/NoteContentBuilder(539): <list><list-item dir="ltr">Surf's up</list-item dir="ltr"></list><list-item dir="ltr">

note: Stuff to see

I removed only a few clean ascii lines but had UI issues with the rich-editor in the emulator (only one backspace at a time). I feel  it's an encoding issue or something closely related like tag corruption by the rich editor.

**Comment by guillaume-d** [comment]
I have exactly the same error with a note containing a < in the 'note-content' tag, it seems no XML text escaping is done when saving to the SD-Card!

The note in the database seems to get encoded correctly: when I correct the /sdcard/tomdroid/<hash>.note file manually, the error comes back again! :(
I guess the DB has priority as it overwrites my correction: any way against this?
