### ISSUE TITLE
NullPointer in Preferences

### ISSUE THREAD

**Issue by obilodeau** [tomboy-notes/tomdroid#108]
From Android Market for Tomdroid 0.4.1.

No user comment.

Stack trace:
java.lang.NullPointerException
at org.tomdroid.util.Preferences.putString(Preferences.java:87)
at org.tomdroid.ui.PreferencesActivity.authenticate(PreferencesActivity.java:119)
at org.tomdroid.ui.PreferencesActivity.access$2(PreferencesActivity.java:116)
at org.tomdroid.ui.PreferencesActivity$2.onPreferenceChange(PreferencesActivity.java:108)
at android.preference.Preference.callChangeListener(Preference.java:756)
at android.preference.EditTextPreference.onDialogClosed(EditTextPreference.java:141)
at android.preference.DialogPreference.onDismiss(DialogPreference.java:384)
at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1047)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)

---

Imported from Launchpad using lp2gh.
- date created: 2010-12-12T22:38:14Z
- owner: plaxx
- the launchpad url was https://bugs.launchpad.net/bugs/689439

**Comment by obilodeau** [comment]
(by obilodeau)
Probably related. in getString instead of putString.

java.lang.NullPointerException
at org.tomdroid.util.Preferences.getString(Preferences.java:79)
at org.tomdroid.sync.SyncManager.getCurrentService(SyncManager.java:68)
at org.tomdroid.sync.SyncManager.startSynchronization(SyncManager.java:63)
at org.tomdroid.ui.Actionbar$1.onClick(Actionbar.java:64)
at android.view.View.performClick(View.java:2408)
at android.view.View$PerformClick.run(View.java:8819)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)

**Comment by obilodeau** [comment]
(by j-4)
Can we close this, since nobody could ever reproduce it?
