### ISSUE TITLE
Sync with SD Card forces the application to close

### ISSUE THREAD

**Issue by obilodeau** [tomboy-notes/tomdroid#162]
HTC Desire A8181, Firmware 2.1-update1, kernel 2.6.29-97da29ed htc-kernel@and18-2 #1

After installation, and on first start of the app, there is a message:

There are no notes in Tomdroid's database. Make sure you copied Tomboy's note files (*.note) in the tomdroid/ directory on your sdcard then press "Menu" and "Sync with SD Card".

I've made one note in tomdroid/ but when I sync I have to force the application to close "The application Tomdroid (process org.tomdroid) has stopped unexpectedly. Please try again."

Hopefully some of the grab from the adb logcat below will help:

D/dalvikvm(  254): GC freed 676 objects / 34664 bytes in 79ms
D/dalvikvm(  170): GC freed 68 objects / 3592 bytes in 102ms
D/dalvikvm(  170): GC freed 59 objects / 3304 bytes in 86ms
W/InputManagerService(   79): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@46862458
W/dalvikvm( 1156): threadid=15: thread exiting with uncaught exception (group=0x4001b390)
E/AndroidRuntime( 1156): Uncaught handler: thread pool-1-thread-1 exiting due to uncaught exception
E/AndroidRuntime( 1156): java.lang.IllegalArgumentException: Invalid UUID stringbb
E/AndroidRuntime( 1156):    at java.util.UUID.fromString(UUID.java:228)
E/AndroidRuntime( 1156):    at org.tomdroid.Note.setGuid(Note.java:139)
E/AndroidRuntime( 1156):    at org.tomdroid.util.AsyncNoteLoaderAndParser$Worker.run(AsyncNoteLoaderAndParser.java:137)
E/AndroidRuntime( 1156):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1068)
E/AndroidRuntime( 1156):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:561)
E/AndroidRuntime( 1156):    at java.lang.Thread.run(Thread.java:1102)
I/Process (   79): Sending signal. PID: 1156 SIG: 3
I/dalvikvm( 1156): threadid=7: reacting to signal 3
I/dalvikvm( 1156): Wrote stack trace to '/data/anr/traces.txt'
I/Process ( 1156): Sending signal. PID: 1156 SIG: 9
W/ContentService(   79): binderDied() at ObserverNode name notes
I/ActivityManager(   79): Process org.tomdroid (pid 1156) has died.
I/WindowManager(   79): WIN DEATH: Window{4688b400 org.tomdroid/org.tomdroid.ui.Tomdroid paused=false}
E/ActivityManager(   79): fail to set top app changed!
D/Sensors (   79): close_akm, fd=141
I/UsageStats(   79): Unexpected resume of com.htc.launcher while already resumed in org.tomdroid
W/InputManagerService(   79): Got RemoteException sending setActive(false) notification to pid 1156 uid 10060
I/JuLOG   (   79): Is it a good time to clear Browser's memory! rec.curAdj=10
D/AK8973  (   61): Compass CLOSE

---

Imported from Launchpad using lp2gh.
- date created: 2010-06-01T07:20:54Z
- owner: ciemon
- the launchpad url was https://bugs.launchpad.net/bugs/588159

**Comment by obilodeau** [comment]
(by benoit.garret)
Does the note filename on your SD Card look like this: 4c8a2dff-c5cb-4739-b929-589da4561e68.note (i.e. seemingly random hexadecimal characters)?

This uid is used to uniquely identify the note, user-defined filenames are not possible right now.

**Comment by obilodeau** [comment]
(by ciemon)
You can close this bug I think.

I didn't have any notes to copy over from my computer to the phone, so made foo.note which was a simple text file. Having now, installed Tomboy, and copied a note into tomdroid/ the errors don't show themselves.

Might I suggest that an initial note is made on the handest as part of the installation of Tomdroid, this will remove this issue if a user doesn't have any notes to copy over to the SD card.
