### ISSUE TITLE
crash when screen goes in power saving

### ISSUE THREAD

**Issue by obilodeau** [tomboy-notes/tomdroid#163]
Reported on the Android Market on tomdroid 0.4.1.

User comment:

stopped when phone blanked screen to save power

Stack trace:
java.lang.IllegalArgumentException: View not attached to window manager
at android.view.WindowManagerImpl.findViewLocked(WindowManagerImpl.java:391)
at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:236)
at android.view.Window$LocalWindowManager.removeView(Window.java:432)
at android.app.Dialog.dismissDialog(Dialog.java:278)
at android.app.Dialog.access$000(Dialog.java:71)
at android.app.Dialog$1.run(Dialog.java:111)
at android.app.Dialog.dismiss(Dialog.java:268)
at org.tomdroid.ui.Tomdroid$2.handleMessage(Tomdroid.java:167)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:144)
at android.app.ActivityThread.main(ActivityThread.java:4937)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)

Not sure if it was while syncing or not.

---

Imported from Launchpad using lp2gh.
- date created: 2010-12-12T22:35:44Z
- owner: plaxx
- the launchpad url was https://bugs.launchpad.net/bugs/689436

**Comment by obilodeau** [comment]
(by j-4)
Can we close this, since nobody could ever reproduce it?
