### ISSUE TITLE
Crash on Sync SD

### ISSUE THREAD

**Issue by obilodeau** [tomboy-notes/tomdroid#177]
Tomdroid 0.7.0 crashes when to try "Sync" notes but there aren't notes on SD

In Settings, Service is on "SD Card".
Steps to reproduce are:
1) In Main Activity, Open Menu.
2) Click on Sync
3) In dialog "Error" click on Save

The obtained exception stacktrace is reported below:

E/AndroidRuntime(  635): FATAL EXCEPTION: main
E/AndroidRuntime(  635): java.lang.NullPointerException
E/AndroidRuntime(  635):    at org.tomdroid.util.ErrorList.save(ErrorList.java:125)
E/AndroidRuntime(  635):    at org.tomdroid.ui.Tomdroid$SyncMessageHandler$1.onClick(Tomdroid.java:776)
E/AndroidRuntime(  635):    at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:159)
E/AndroidRuntime(  635):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(  635):    at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime(  635):    at android.app.ActivityThread.main(ActivityThread.java:3683)
E/AndroidRuntime(  635):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(  635):    at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime(  635):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
E/AndroidRuntime(  635):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime(  635):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(   68):   Force finishing activity org.tomdroid/.ui.Tomdroid

---

Imported from Launchpad using lp2gh.
- date created: 2012-08-22T00:20:24Z
- owner: rame276
- the launchpad url was https://bugs.launchpad.net/bugs/1039817

**Comment by obilodeau** [comment]
(by noahy)
I can't reproduce this; do you have any information about what the error is that it's trying to save?  I think I can create a workaround, but I'm not sure.  Please try the latest code and let me know if it is fixed.

**Comment by obilodeau** [comment]
(by j-4)
Fix committed -> does this mean, with the newest code you do not see this error any more?

**Comment by obilodeau** [comment]
(by rame276)
Tomdroid 0.7.1 don't crashes :)
Good work!

P.S.:
I like the new look of version 0.7.1
