### ISSUE TITLE
Rev 454 (new sync). Sync dialogue is not removed after sdcard sync on Android 1.6

### ISSUE THREAD

**Issue by obilodeau** [tomboy-notes/tomdroid#188]
After sd card sync the sync dialog does not dissapear on android 1.6 (at least, havent tried others).

Here the log:

09-07 05:55:02.337: I/SdCardSyncService(346): Path /sdcard/tomdroid exists: true
09-07 05:55:02.367: D/SdCardSyncService(346): parsing note. filename: 9b9ee8aa-f59f-415e-98b2-704ea9612b11.note
09-07 05:55:02.427: D/NoteManager(346): stripped the title from note-content
09-07 05:55:02.427: D/SdCardSyncService(346): parsing note. filename: f2ed651f-c545-444d-a827-ce21e5d3894e.note
09-07 05:55:02.437: D/NoteManager(346): stripped the title from note-content
09-07 05:55:02.457: D/SdCardSyncService(346): parsing note. filename: b3af2a14-dfda-4ba6-a86c-41bb670e160e.note
09-07 05:55:02.477: D/NoteManager(346): stripped the title from note-content
09-07 05:55:02.487: D/SdCardSyncService(346): parsing note. filename: 1331e52c-0a35-4c89-90c7-507bc9a2f61a.note
09-07 05:55:02.518: D/dalvikvm(346): GREF has increased to 301
09-07 05:55:02.518: D/NoteManager(346): stripped the title from note-content
09-07 05:55:02.537: D/SdCardSyncService(346): parsing note. filename: 2b38427e-7883-455c-919d-0e99106fdfb2.note
09-07 05:55:02.557: D/NoteManager(346): stripped the title from note-content
09-07 05:55:02.557: D/SdCardSyncService(346): parsing note. filename: c9ba327b-8f5d-44fa-9866-e56b5b1e308b.note
09-07 05:55:02.567: D/NoteManager(346): stripped the title from note-content
09-07 05:55:02.587: D/SdCardSyncService(346): parsing note. filename: 682a1597-34da-42e6-94db-c6916e95d325.note
09-07 05:55:02.607: D/NoteManager(346): stripped the title from note-content
09-07 05:55:02.607: D/SdCardSyncService(346): parsing note. filename: c50ed79b-5ce9-4beb-ba43-a512f756737f.note
09-07 05:55:02.617: D/NoteManager(346): stripped the title from note-content
09-07 05:55:02.636: D/SdCardSyncService(346): parsing note. filename: 0b234c28-d12b-47fd-9ebe-1681e7cc152a.note
09-07 05:55:02.667: D/NoteManager(346): stripped the title from note-content
09-07 05:55:02.677: D/SdCardSyncService(346): parsing note. filename: 1f4f4b14-ed19-42d6-9fd5-e29f23381468.note
09-07 05:55:02.677: D/dalvikvm(346): GREF has increased to 401
09-07 05:55:02.697: D/NoteManager(346): stripped the title from note-content
09-07 05:55:02.697: D/SdCardSyncService(346): parsing note. filename: 038a5344-c8ef-4f0c-96e6-ea232aad42ab.note
09-07 05:55:02.717: W/SdCardSyncService(346): Something went wrong trying to grab the note-content out of a note
09-07 05:55:02.727: D/SdCardSyncService(346): parsing note. filename: e4583caa-e477-42d6-b8d1-06acbdec4bd3.note
09-07 05:55:02.737: W/System.err(346): org.apache.harmony.xml.ExpatParser$ParseException: At line 8, column 21: mismatched tag
09-07 05:55:02.757: W/System.err(346):  at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:492)
09-07 05:55:02.757: W/System.err(346):  at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:477)
09-07 05:55:02.767: W/System.err(346):  at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:317)
09-07 05:55:02.767: W/System.err(346):  at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:273)
09-07 05:55:02.767: W/System.err(346):  at org.tomdroid.sync.sd.SdCardSyncService$Worker.run(SdCardSyncService.java:214)
09-07 05:55:02.767: W/System.err(346):  at org.tomdroid.sync.SyncService$1.run(SyncService.java:169)
09-07 05:55:02.767: W/System.err(346):  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:648)
09-07 05:55:02.767: W/System.err(346):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:673)
09-07 05:55:02.767: W/System.err(346):  at java.lang.Thread.run(Thread.java:1060)
09-07 05:55:02.807: D/SdCardSyncService(346): parsing note. filename: 4dfce710-d1e6-4271-b404-a44b49686566.note
09-07 05:55:02.827: W/System.err(346): org.apache.harmony.xml.ExpatParser$ParseException: At line 6, column 29: mismatched tag
09-07 05:55:02.866: W/System.err(346):  at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:492)
09-07 05:55:02.876: W/System.err(346):  at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:477)
09-07 05:55:02.876: W/System.err(346):  at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:317)
09-07 05:55:02.876: W/System.err(346):  at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:273)
09-07 05:55:02.896: W/System.err(346):  at org.tomdroid.sync.sd.SdCardSyncService$Worker.run(SdCardSyncService.java:214)
09-07 05:55:02.896: W/System.err(346):  at org.tomdroid.sync.SyncService$1.run(SyncService.java:169)
09-07 05:55:02.896: W/System.err(346):  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:648)
09-07 05:55:02.896: W/System.err(346):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:673)
09-07 05:55:02.896: W/System.err(346):  at java.lang.Thread.run(Thread.java:1060)
09-07 05:55:02.906: D/SdCardSyncService(346): parsing note. filename: 5a3fb21e-2410-42da-95d3-4fb6d4187aca.note
09-07 05:55:02.936: W/System.err(346): org.apache.harmony.xml.ExpatParser$ParseException: At line 3, column 32: mismatched tag
09-07 05:55:03.000: W/System.err(346):  at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:492)
09-07 05:55:03.000: W/System.err(346):  at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:477)
09-07 05:55:03.017: W/System.err(346):  at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:317)
09-07 05:55:03.017: W/System.err(346):  at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:273)
09-07 05:55:03.017: W/System.err(346):  at org.tomdroid.sync.sd.SdCardSyncService$Worker.run(SdCardSyncService.java:214)
09-07 05:55:03.017: W/System.err(346):  at org.tomdroid.sync.SyncService$1.run(SyncService.java:169)
09-07 05:55:03.017: W/System.err(346):  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:648)
09-07 05:55:03.017: W/System.err(346):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:673)
09-07 05:55:03.017: W/System.err(346):  at java.lang.Thread.run(Thread.java:1060)
09-07 05:55:03.027: D/SdCardSyncService(346): parsing note. filename: 005bfc5c-75a8-4b9a-920b-a05e88509d5e.note
09-07 05:55:03.187: D/dalvikvm(346): GREF has increased to 501
09-07 05:55:03.648: D/SyncService(346): Notes to pull: 11, Notes to push: 0, Notes to delete: 0, Notes to compare: 0
09-07 05:55:03.687: V/NoteManager(346): A new note has been detected (not yet in db)
09-07 05:55:03.767: V/NoteManager(346): Note inserted in content provider. ID: content://org.tomdroid.notes/notes/1 TITLE:Timezone parsing bug GUID:9b9ee8aa-f59f-415e-98b2-704ea9612b11
09-07 05:55:03.836: V/NoteManager(346): A new note has been detected (not yet in db)
09-07 05:55:03.866: V/NoteManager(346): Note inserted in content provider. ID: content://org.tomdroid.notes/notes/2 TITLE:test Notebook Template GUID:f2ed651f-c545-444d-a827-ce21e5d3894e
09-07 05:55:03.916: V/NoteManager(346): A new note has been detected (not yet in db)
09-07 05:55:03.977: V/NoteManager(346): Note inserted in content provider. ID: content://org.tomdroid.notes/notes/3 TITLE:tomdroid bug483101 GUID:b3af2a14-dfda-4ba6-a86c-41bb670e160e
09-07 05:55:04.007: V/NoteManager(346): A new note has been detected (not yet in db)
09-07 05:55:04.088: V/NoteManager(346): Note inserted in content provider. ID: content://org.tomdroid.notes/notes/4 TITLE:Test Case GUID:1331e52c-0a35-4c89-90c7-507bc9a2f61a
09-07 05:55:04.567: D/dalvikvm(346): GC freed 11611 objects / 954712 bytes in 404ms
09-07 05:55:04.587: V/NoteManager(346): A new note has been detected (not yet in db)
09-07 05:55:04.738: V/NoteManager(346): Note inserted in content provider. ID: content://org.tomdroid.notes/notes/5 TITLE:Worklog GUID:2b38427e-7883-455c-919d-0e99106fdfb2
09-07 05:55:04.757: D/dalvikvm(346): GREF has decreased to 399
09-07 05:55:04.757: D/dalvikvm(346): GREF has decreased to 299
09-07 05:55:04.807: V/NoteManager(346): A new note has been detected (not yet in db)
09-07 05:55:04.866: V/NoteManager(346): Note inserted in content provider. ID: content://org.tomdroid.notes/notes/6 TITLE:In another notebook? GUID:c9ba327b-8f5d-44fa-9866-e56b5b1e308b
09-07 05:55:04.906: V/NoteManager(346): A new note has been detected (not yet in db)
09-07 05:55:04.966: V/NoteManager(346): Note inserted in content provider. ID: content://org.tomdroid.notes/notes/7 TITLE:test & validate bug 364850 GUID:682a1597-34da-42e6-94db-c6916e95d325
09-07 05:55:04.997: V/NoteManager(346): A new note has been detected (not yet in db)
09-07 05:55:05.057: V/NoteManager(346): Note inserted in content provider. ID: content://org.tomdroid.notes/notes/8 TITLE:Linked note GUID:c50ed79b-5ce9-4beb-ba43-a512f756737f
09-07 05:55:05.087: V/NoteManager(346): A new note has been detected (not yet in db)
09-07 05:55:05.137: V/NoteManager(346): Note inserted in content provider. ID: content://org.tomdroid.notes/notes/9 TITLE:Worklog-1-23-10 GUID:0b234c28-d12b-47fd-9ebe-1681e7cc152a
09-07 05:55:05.187: V/NoteManager(346): A new note has been detected (not yet in db)
09-07 05:55:05.227: V/NoteManager(346): Note inserted in content provider. ID: content://org.tomdroid.notes/notes/10 TITLE:TopNote GUID:1f4f4b14-ed19-42d6-9fd5-e29f23381468
09-07 05:55:05.277: V/NoteManager(346): A new note has been detected (not yet in db)
09-07 05:55:05.307: V/NoteManager(346): Note inserted in content provider. ID: content://org.tomdroid.notes/notes/11 TITLE:Hipo Notebook Template GUID:005bfc5c-75a8-4b9a-920b-a05e88509d5e
09-07 05:55:05.347: V/SyncService(346): sync progress: 70
09-07 05:55:05.367: V/SyncService(346): sync progress: 100

---

Imported from Launchpad using lp2gh.
- date created: 2012-09-07T06:01:28Z
- owner: j-4
- the launchpad url was https://bugs.launchpad.net/bugs/1047179

**Comment by obilodeau** [comment]
(by noahy)
Sorry, should have paid more attention to SD card before committing... should work now.
