### ISSUE TITLE
sync conflict - then crash

### ISSUE THREAD

**Issue by obilodeau** [tomboy-notes/tomdroid#211]
I'm using Tomdroid 0.7.5 with  Grauphel 0.4.0 for about 2 Month.
recently Tomdroid came up the first time with a sync conflict between the server the local data (I don't really know why).  Tomdroid shows me where the conflicts are (there are many lines)  and gives me the choice which data to keep or to replace.
 I select, keep the server data, but then Tomdroid crashes. 
The same happens when I chose to make a copy of the note. 
Now I'm stuck with that screen and can't get to my notes list. There is no "cancel" button there (I guess it would be good if there would be one there).  Ah, I just noticed that I would have to go back and provoke the sync window to come up. then I can cancel the syncing and get to my notes. Still IMO there should be a cancel button on that conflict screen.
When I've canceled the process and I'm in the notes list and syncronise, THEN all of a sudden it syncs ok.
So I don't know why the conflict was there in the first place. But at least I found out that the above way solves the issue.

---

Imported from Launchpad using lp2gh.
- date created: 2015-03-09T07:23:44Z
- owner: hermann-san
- the launchpad url was https://bugs.launchpad.net/bugs/1429735

**Comment by obilodeau** [comment]
(by peter-frohberg)
I've experienced the same issue. Thanks for the workaround tip Hermann San.

Environment-Setup: 
- Server: Grauphel 0.5.0 (on owncloud 0.8.3)
- Client: Motorola Moto G, Android 4.4.4

Is there any chance to get a log? I'm not familiar with android development, but I would love to help solving this major(!) bug.

**Comment by obilodeau** [comment]
(by khertan)
I m experiencing same issue.

This happen only when sync is initiated at start of the app.
So when this happen all options give a crash.

The workarround is to cancel sync via physical back button when tomdroid ask for a choice on a sync conflict.
If i cancel sync before TomDroid also crash. And then after i can manually sync and resolve conflict.

TomDroid is still maintained ?

Using Grauphel 0.5.0 and TomDroid 0.7.5 on a galaxy a3 with Android 5.0.2
(Was getting similar crash with Blackberry z10 and their android runtime)

**Comment by obilodeau** [comment]
(by khertan)
08-20 10:33:26.026: E/AndroidRuntime(7327): FATAL EXCEPTION: main
08-20 10:33:26.026: E/AndroidRuntime(7327): Process: org.tomdroid, PID: 7327
08-20 10:33:26.026: E/AndroidRuntime(7327): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference
08-20 10:33:26.026: E/AndroidRuntime(7327):     at org.tomdroid.sync.SyncService.addPullable(SyncService.java:589)
08-20 10:33:26.026: E/AndroidRuntime(7327):     at org.tomdroid.ui.CompareNotes.pullNote(CompareNotes.java:494)
08-20 10:33:26.026: E/AndroidRuntime(7327):     at org.tomdroid.ui.CompareNotes.onChooseNote(CompareNotes.java:461)
08-20 10:33:26.026: E/AndroidRuntime(7327):     at org.tomdroid.ui.CompareNotes$3.onClick(CompareNotes.java:310)
08-20 10:33:26.026: E/AndroidRuntime(7327):     at android.view.View.performClick(View.java:5210)
08-20 10:33:26.026: E/AndroidRuntime(7327):     at android.view.View$PerformClick.run(View.java:20976)
08-20 10:33:26.026: E/AndroidRuntime(7327):     at android.os.Handler.handleCallback(Handler.java:739)
08-20 10:33:26.026: E/AndroidRuntime(7327):     at android.os.Handler.dispatchMessage(Handler.java:95)
08-20 10:33:26.026: E/AndroidRuntime(7327):     at android.os.Looper.loop(Looper.java:145)
08-20 10:33:26.026: E/AndroidRuntime(7327):     at android.app.ActivityThread.main(ActivityThread.java:6145)
08-20 10:33:26.026: E/AndroidRuntime(7327):     at java.lang.reflect.Method.invoke(Native Method)
08-20 10:33:26.026: E/AndroidRuntime(7327):     at java.lang.reflect.Method.invoke(Method.java:372)
08-20 10:33:26.026: E/AndroidRuntime(7327):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
08-20 10:33:26.026: E/AndroidRuntime(7327):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by obilodeau** [comment]
(by tobias-kaminsky)
Same for me:
                                                            Process: org.tomdroid, PID: 7403
                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference
                                                                at org.tomdroid.sync.SyncService.addPullable(SyncService.java:589)
                                                                at org.tomdroid.ui.CompareNotes.pullNote(CompareNotes.java:494)
                                                                at org.tomdroid.ui.CompareNotes.onChooseNote(CompareNotes.java:461)
                                                                at org.tomdroid.ui.CompareNotes$4.onClick(CompareNotes.java:327)
                                                                at android.view.View.performClick(View.java:5198)
                                                                at android.view.View$PerformClick.run(View.java:21150)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:148)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5466)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by nomeata** [comment]
I am also affected by this.

**Comment by cweiske** [comment]
Same here :/
