### ISSUE TITLE
Error parsing response from Online Synchronization

### ISSUE THREAD

**Issue by praet0ri4n** [tomboy-notes/tomdroid#225]
Hi,

I am getting a "Error parsing response from Online Synchronization" against dockerized Nextcloud 18 + grauphel Tomboy Web server app behind nginx proxy.
The weird part is that synchronization works over WiFi, but not over 4g mobile network.

Android app: Tomdroid 0.7.5
Logcat on my phone says nothing as well as the server logs of docker, nextcloud, or mysql database.
My notes count is above 850+

Te issue could be related to
https://github.com/tomboy-notes/tomdroid/issues/53
https://github.com/tomboy-notes/tomdroid/issues/17

Whre to look for another clues? Thanks!

**Comment by praet0ri4n** [comment]
Sorry
adb logcat:

08-14 23:22:45.255 16223 16629 I WebConnection: Sending http-header: X-Tomboy-Client: org.tomdroid v0.7.5, build 14, Android v7.0, HUAWEI/FRD-L09
08-14 23:22:45.292   431  1337 I gralloc : alloc_device_alloc:564: Alloc handle(0x7f08a35900): interfmt=1, stride=1088, size=2752512, usage=0x933
08-14 23:22:45.319   431  1337 I gralloc : alloc_device_alloc:564: Alloc handle(0x7f08a47200): interfmt=1, stride=1088, size=2752512, usage=0x933
08-14 23:22:45.331   431  1432 I gralloc : alloc_device_alloc:564: Alloc handle(0x7f03280300): interfmt=1, stride=1088, size=2752512, usage=0x933
08-14 23:22:45.475 16223 16629 W DefaultRequestDirector: Authentication error: Unable to respond to any of these challenges: {}
08-14 23:22:45.475 16223 16629 I WebConnection: Response status : HTTP/1.1 401 Unauthorized
08-14 23:22:45.476 16223 16629 I WebConnection: Received : oauth_problem=signature_invalid&debug_sbs=GET&http%3A%2F%2F**********%3A9876%2Fowncloud%2Findex.php%2Fapps%2Fgrauphel%2Fapi%2F1.0%2Fpraet0ri4n&oauth_consumer_key%3Danyone%26oauth_nonce%3D-4471689293734163006%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1597440165%26oauth_token%3Da394fa6f96b9ef59b%26oauth_version%3D1.0
08-14 23:22:45.477 16223 16629 E SnowySyncService: Problem parsing the server response
08-14 23:22:45.477 16223 16629 E SnowySyncService: org.json.JSONException: Value oauth_problem of type java.lang.String cannot be converted to JSONObject
08-14 23:22:45.477 16223 16629 E SnowySyncService: 	at org.json.JSON.typeMismatch(JSON.java:111)
08-14 23:22:45.477 16223 16629 E SnowySyncService: 	at org.json.JSONObject.<init>(JSONObject.java:160)
08-14 23:22:45.477 16223 16629 E SnowySyncService: 	at org.json.JSONObject.<init>(JSONObject.java:173)
08-14 23:22:45.477 16223 16629 E SnowySyncService: 	at org.tomdroid.sync.web.SnowySyncService$3.run(SnowySyncService.java:196)
08-14 23:22:45.477 16223 16629 E SnowySyncService: 	at org.tomdroid.sync.SyncService$1.run(SyncService.java:170)
08-14 23:22:45.477 16223 16629 E SnowySyncService: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-14 23:22:45.477 16223 16629 E SnowySyncService: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)


Does this mean, that the connection request from WiFi / 4G result in different access requests? It needs different access tokens?

The same request made ofer wifi gets:
08-14 23:25:43.253 16223 17273 I WebConnection: Sending http-header: X-Tomboy-Client: org.tomdroid v0.7.5, build 14, Android v7.0, HUAWEI/FRD-L09
08-14 23:25:43.289   431   444 I gralloc : alloc_device_alloc:564: Alloc handle(0x7f08a41500): interfmt=1, stride=1088, size=2752512, usage=0x933
08-14 23:25:43.321   431  1432 I gralloc : alloc_device_alloc:564: Alloc handle(0x7f08a40c00): interfmt=1, stride=1088, size=2752512, usage=0x933
08-14 23:25:43.347  1206  1206 I TrafficMonitor: update:rxPkts:25,txPkts:24,rxBytes:8768,txBytes:2357
08-14 23:25:43.347  1206  1206 I TrafficMonitor: start expired. level:-1
08-14 23:25:43.347  1206  1206 I TrafficMonitor: gettimer:interval=2000
08-14 23:25:43.376   430   430 E ServiceManager: try to find service failed, not allowed access from isolated processes.
08-14 23:25:43.379  4434  4449 I ServiceManager: Waiting for service SurfaceFlinger...
08-14 23:25:43.424 16223 17273 I WebConnection: Response status : HTTP/1.1 200 OK
08-14 23:25:43.425 16223 17273 I WebConnection: Received : {"user-name":"*******","first-name":null,"last-name":null,"notes-ref":{"api-ref":"https:\/\/*******:9876\/owncloud\/index.php\/apps\/grauphel\/api\/1.0\/********\/notes","href":"https:\/\/**********:9876\/owncloud\/index.php\/apps\/grauphel\/"},"latest-sync-revision":11,"current-sync-guid":"*******-5f345606277683.76428085"}
....

**Comment by praet0ri4n** [comment]
Ok obviously this issue belongs to grauphel and oauth handling.. Closing this issue here
