### ISSUE TITLE
One-way sync with Ubuntu One fails if notes were created on U1

### ISSUE THREAD

**Issue by obilodeau** [tomboy-notes/tomdroid#45]
No problem getting sync to download notes, but force closes (org.tomdroid) when sync completes. 3rd time was a big crash and shut down my G2.

---

Imported from Launchpad using lp2gh.
- date created: 2010-10-09T21:43:23Z
- owner: elysium-pacbell
- assignee: plaxx
- the launchpad url was https://bugs.launchpad.net/bugs/657477

**Comment by obilodeau** [comment]
(by obilodeau)
I never used sync aside to test it earlier today with an empty server note list. I'll be away for next few days with no Internet access, hopefully someone else will be able to help you otherwise I advise you to downgrade or start troubleshooting yourself.

**Comment by obilodeau** [comment]
(by elysium-pacbell)
Thanks for the quick reply. FYI, the same problem when syncing fo SD card. I think I will stay wth .4 becasue the theme is more pleasing. Also note that there is a slight formatiing glitch that was not present in the previous version - text indents are much shorter that they shoud be, and the secondary indent is almost indistinguishable from the primary one (no deeper indent and no change of bullet style.) Enjoy the autumn colors!

**Comment by obilodeau** [comment]
(by trappe)
Hi Sorondors,

could you provide the log output of the force close? Simply run

$ adb logcat

while reproducing the crash should work fine.

**Comment by obilodeau** [comment]
(by gerhard-rauniak-gmail)
Hi Olivier!

First I want to say thanks for your work. Tomdroid is really great.

I think I have the same problem as Sorondors with my HTC Desire and Android 2.2. Below you can find the adb logcat output. I hope it's correct because it was the first time I used adb. 

I/ActivityManager(   92): Starting activity: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.tomdroid/.ui.Tomdroid }
D/AK8973  (   72): Compass Start
D/Sensors (   92): open_akm, fd=149
I/ActivityManager(   92): Displayed activity org.tomdroid/.ui.Tomdroid: 115 ms (total 115 ms)
W/Rosie   (  196): mAddHtcWidgetByOtherActivity = false, mIsOpenSlideWhenLeaveLaunch = true
W/InputManagerService(   92): Ignoring hideSoftInput of: com.android.internal.view.IInputMethodClient$Stub$Proxy@4668a980
V/SyncService(17299): sync progress: 0
V/SnowySyncService(17299): Loading Snowy notes
D/dalvikvm(17299): GC_FOR_MALLOC freed 5169 objects / 303904 bytes in 47ms
I/WebConnection(17299): Response status : HTTP/1.1 200 OK
I/global  (17299): Default buffer size used in BufferedReader constructor. It would be better to be explicit if an 8k-char buffer is required.
I/WebConnection(17299): Received : {"user-name": "https://login.launchpad.net/+id/xwLseLR", "last-name": "my account", "notes-ref": {"href": "https://one.ubuntu.com/notes/", "api-ref": "https://one.ubuntu.com/notes/api/1.0/op/"}, "current-sync-guid": "0", "first-name": "my account", "latest-sync-revision": 13}
V/SyncService(17299): sync progress: 30
D/dalvikvm(17299): GC_FOR_MALLOC freed 6123 objects / 377752 bytes in 41ms
D/dalvikvm(17299): GC_FOR_MALLOC freed 1106 objects / 237712 bytes in 38ms
D/NativeCrypto(17299): Freeing OpenSSL session
D/dalvikvm( 7973): GC_EXPLICIT freed 1467 objects / 83352 bytes in 86ms
E/Database( 7973): close() was never explicitly called on database '/data/data/com.handyapps.easymoney/databases/data' 
E/Database( 7973): android.database.sqlite.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
E/Database( 7973):  at android.database.sqlite.SQLiteDatabase.<init>(SQLiteDatabase.java:1900)
E/Database( 7973):  at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:884)
E/Database( 7973):  at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:918)
E/Database( 7973):  at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:911)
E/Database( 7973):  at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:548)
E/Database( 7973):  at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:203)
E/Database( 7973):  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:98)
E/Database( 7973):  at com.handyapps.easymoney.DbAdapter.open(DbAdapter.java:925)
E/Database( 7973):  at com.handyapps.easymoney.AlarmService_Service$1.run(AlarmService_Service.java:162)
E/Database( 7973):  at java.lang.Thread.run(Thread.java:1102)
I/WebConnection(17299): Response status : HTTP/1.1 200 OK
I/global  (17299): Default buffer size used in BufferedReader constructor. It would be better to be explicit if an 8k-char buffer is required.
I/WebConnection(17299): Received : {"notes": [{"guid": "c38aa0e15b66446b9f771ddf6878b840", "ref": {"href": "https://one.ubuntu.com/notes/edit/c38aa0e15b66446b9f771ddf6878b840", "api-ref": "https://one.ubuntu.com/notes/api/1.0/op/c38aa0e15b66446b9f771ddf6878b840"}, "title": "Joomla local"}, {"guid": "5de9006b-67f6-4564-95e8-1eb6e0e5e9a4", "ref": {"href": "https://one.ubuntu.com/notes/edit/5de9006b-67f6-4564-95e8-1eb6e0e5e9a4", "api-ref": "https://one.ubuntu.com/notes/api/1.0/op/5de9006b-67f6-4564-95e8-1eb6e0e5e9a4"}, "title": "Software Ubuntu Installation"}, {"guid": "277e51e8-f449-437e-854e-aaf90c5e37db", "ref": {"href": "https://one.ubuntu.com/notes/edit/277e51e8-f449-437e-854e-aaf90c5e37db", "api-ref": "https://one.ubuntu.com/notes/api/1.0/op/277e51e8-f449-437e-854e-aaf90c5e37db"}, "title": "Stromverbrauch"}, {"guid": "f9be0855-c14c-4761-8b00-cea2ad48ad42", "ref": {"href": "https://one.ubuntu.com/notes/edit/f9be0855-c14c-4761-8b00-cea2ad48ad42", "api-ref": "https://one.ubuntu.com/notes/api/1.0/op/f9be0855-c14c-4761-8b00-cea2ad48ad42"}, "title": "Qnap TS-110"}], "latest-sync-revision": 13}
V/SyncService(17299): sync progress: 35
D/dalvikvm(17299): GC_FOR_MALLOC freed 5309 objects / 339304 bytes in 41ms
D/NativeCrypto(17299): Freeing OpenSSL session
D/dalvikvm(17299): GC_FOR_MALLOC freed 1196 objects / 251168 bytes in 34ms
I/WebConnection(17299): Response status : HTTP/1.1 200 OK
I/global  (17299): Default buffer size used in BufferedReader constructor. It would be better to be explicit if an 8k-char buffer is required.
I/WebConnection(17299): Received : {"notes": [{"note-content": "1. Install Apache Server \n<list><list-item dir=\"ltr\">link:urlhttp://wiki.ubuntuusers.de/Apache/link:url</list-item></list>\n2. Installation PHP\n<list><list-item dir=\"ltr\">link:urlhttp://wiki.ubuntuusers.de/PHP/link:url</list-item></list>\n3. Installation MySQL\n<list><list-item dir=\"ltr\">link:urlhttp://wiki.ubuntuusers.de/MySQL/link:url</list-item></list>\n4. Installation MySQL GUI\n<list><list-item dir=\"ltr\">link:urlhttp://wiki.ubuntuusers.de/MySQL/Werkzeuge/link:url</list-item></list>", "open-on-startup": false, "last-metadata-change-date": "2010-07-13T22:25:10.0774270+02:00", "title": "Joomla local", "tags": [], "last-sync-revision": 3, "note-content-version": 1.0, "last-change-date": "2010-07-21T18:43:12", "guid": "c38aa0e15b66446b9f771ddf6878b840", "ref": {"href": "https://one.ubuntu.com/notes/edit/c38aa0e15b66446b9f771ddf6878b840", "api-ref": "https://one.ubuntu.com/notes/api/1.0/op/c38aa0e15b66446b9f771ddf6878b840"}, "pinned": false}, {"note-content": "1. ING\n\n2. Calibre\n\n", "open-on-startup": false, "last-metadata-change-date": "2010-08-22T10:13:24.5757980+02:00", "title": "Software Ubuntu Installation", "tags": [], "create-date": "2010-08-18T15:46:38.6766470+02:00", "last-sync-revision": 8, "note-content-version": 1.0, "last-change-date": "2010-08-22T10:13:24.5757980+02:00", "guid": "5de9006b-67f6-4564-95e8-1eb6e0e5e9a4", "ref": {"href": "https://one.ubuntu.com/notes/edit/5de9006b-67f6-4564-95e8-1eb6e0e5e9a4", "api-ref": "https://one.ubuntu.com/notes/api/1.0/op/5de9006b-67f6-4564-95e8-1eb6e0e5e9a4"}, "pinned": false}, {"note-content": "Rooter, Skype Telefon   13,5W\n", "open-on-startup": false, "last-metadata-change-date": "2010-09-04T10:47:52.2521690+02:00", "title": "Stromverbrauch", "tags": [], "create-date": "2010-09-04T10:47:23.9114800+02:00", "last-sync-revision": 10, "note-content-version": 1.0, "last-change-date": "2010-09-04T10:47:52.2521690+02:00", "guid": "277e51e8-f449-437e-854e-aaf90c5e37db", "ref": {"href": "https://one.ubuntu.com/notes/edit/277e51e8-f449-437e-854e-aaf90c5e37db", "api-ref": "https://one.ubuntu.com/notes/api/1.0/op/277e51e8-f449-437e-854e-aaf90c5e37db"}, "pinned": false}, {"note-content": "229,-\n\nHosting 54,-\n\n\n", "open-on-startup": false, "last-metadata-change-date": "2010-10-10T19:55:46.2529570+02:00", "title": "Qnap TS-110", "tags": [], "create-date": "2010-08-26T21:54:41.6476700+02:00", "last-sync-revision": 13, "note-content-version": 1.0, "last-change-date": "2010-10-10T19:55:46.2529570+02:00", "guid": "f9be0855-c14c-4761-8b00-cea2ad48ad42", "ref": {"href": "https://one.ubuntu.com/notes/edit/f9be0855-c14c-4761-8b00-cea2ad48ad42", "api-ref": "https://one.ubuntu.com/notes/api/1.0/op/f9be0855-c14c-4761-8b00-cea2ad48ad42"}, "pinned": false}], "latest-sync-revision": 13}
V/SyncService(17299): sync progress: 60
D/SyncService(17299): Cursor returned null or 0 notes
V/SyncService(17299): sync progress: 70
W/dalvikvm(17299): threadid=7: thread exiting with uncaught exception (group=0x400259f8)
E/AndroidRuntime(17299): FATAL EXCEPTION: pool-9-thread-1
E/AndroidRuntime(17299): java.lang.IllegalArgumentException: Invalid UUID stringc38aa0e15b66446b9f771ddf6878b840
E/AndroidRuntime(17299):    at java.util.UUID.fromString(UUID.java:228)
E/AndroidRuntime(17299):    at org.tomdroid.Note.setGuid(Note.java:169)
E/AndroidRuntime(17299):    at org.tomdroid.Note.<init>(Note.java:90)
E/AndroidRuntime(17299):    at org.tomdroid.sync.web.SnowySyncService$3.run(SnowySyncService.java:189)
E/AndroidRuntime(17299):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1068)
E/AndroidRuntime(17299):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:561)
E/AndroidRuntime(17299):    at java.lang.Thread.run(Thread.java:1102)
W/ActivityManager(   92):   Force finishing activity org.tomdroid/.ui.Tomdroid
D/Sensors (   92): close_akm, fd=149
D/AK8973  (   72): Compass CLOSE 
I/Process (17299): Sending signal. PID: 17299 SIG: 9
I/ActivityManager(   92): Process org.tomdroid (pid 17299) has died.

**Comment by obilodeau** [comment]
(by obilodeau)
Gerhard, your issue has been documented and fixed in a separate branch already (see tomdroid-dev mailing list for details). I'm going to release a 0.4.1 Wednesday evening EDT which fixes this.

Sorodoros, is this your issue? If not, please let us know what it is.

Thanks!

**Comment by obilodeau** [comment]
(by elysium-pacbell)
Not certain, because I have not run the adb logcat (not sure how to do that), but the "org.tomdroid" reference in Gerhard's log seems to suggest at least a similar issue, if not the same issue. Let's see how.4.1 goes and we can have another look if the problem persists. There are also minor formatting issues in .4 as well, and am wondering if they have also been fixed???

Thans for your attention to this!

sorodoros

**Comment by obilodeau** [comment]
(by gerhard-rauniak-gmail)
Olivier,

Many thanks for the fast reply. Now I will join the mailinglist. :-)

Gerhard

**Comment by obilodeau** [comment]
(by gerhard-rauniak-gmail)
I just built it from lp:~sil/tomdroid/handle-non-guid-note-ids and it works perfect!

Thanks,

Gerhard

**Comment by obilodeau** [comment]
(by obilodeau)
@sorodoros, can you file a separate issue for your formatting issues and upload a picture of your phone. I have a screenshot on my other PC I will upload later there as well for comparison.

**Comment by obilodeau** [comment]
(by obilodeau)
Sorry I won't release a 0.4.1 now because I want to confirm/fix another bug before I do so. There's a debug APK available as an attachment in lp:659779 that fixes the issue here try it out if you think you are affected by the bug described here.

**Comment by obilodeau** [comment]
(by elysium-pacbell)
Olivier, no worries. Do you intend to update the indent formatting issues in 0.4.1, too? I posted another reply in that bug too further clarify the indent issue. Thx. sorodoros

**Comment by obilodeau** [comment]
(by obilodeau)
No, the 0.4.1 will focus on providing the fix for crasher bugs. I saw your
update regarding the indent formatting. Thank you.

**Comment by obilodeau** [comment]
(by elysium-pacbell)
0.4.1 = good sync with U1. :)

sorodoros

**Comment by obilodeau** [comment]
(by obilodeau)
fix released in 0.4.1
