### ISSUE TITLE
NullPointerException on SD Csrd sync with notes causing parse error

### ISSUE THREAD

**Issue by obilodeau** [tomboy-notes/tomdroid#49]
Tested on 4.0 emulator.

Steps to reproduce:
1. Sync notes from sdcard.img that can be found in repository.

After displaying progress dialog tomdroid crashes with NullPointerException

Application crashes because of NullPointerException
08-20 13:04:30.637: ERROR/SyncService(551): Problem syncing in thread
        java.lang.NullPointerException
        at org.tomdroid.sync.SyncService.sendMessage(SyncService.java:519)
        at org.tomdroid.sync.sd.SdCardSyncService.access$300(SdCardSyncService.java:47)
        at org.tomdroid.sync.sd.SdCardSyncService$Worker.run(SdCardSyncService.java:220)
        at org.tomdroid.sync.SyncService$1.run(SyncService.java:156)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)

---

Imported from Launchpad using lp2gh.
- date created: 2012-08-20T11:08:23Z
- owner: mcveat
- assignee: mcveat
- the launchpad url was https://bugs.launchpad.net/bugs/1038968

**Comment by obilodeau** [comment]
(by j-4)
In which series is this bug present? stable or beta? I think, i mixed things up before.

**Comment by obilodeau** [comment]
(by mcveat)
I found it in beta branch code.

**Comment by obilodeau** [comment]
(by noahy)
This should be fixed in revision 393.

I'm rejecting the merge request, because I think it doesn't solve the problem.  If there is a payload, we need to create the syncErrors and add the payload to the empty error list before sending the message.

Let me know if the bug still persists.
