### ISSUE TITLE
unable to parse response: TimeFormatException

### ISSUE THREAD

**Issue by obilodeau** [tomboy-notes/tomdroid#57]
Reported by rsyring in #1051294 (https://bugs.launchpad.net/tomdroid/+bug/1051294/comments/19):

Ok, here is the log output, sorry it took so long:

12-31 17:05:03.916 8119 9172 E SyncService: Problem syncing in thread
12-31 17:05:03.916 8119 9172 E SyncService: android.util.TimeFormatException: Unexpected length; should be 33 characters
12-31 17:05:03.916 8119 9172 E SyncService: at android.text.format.Time.nativeParse3339(Native Method)
12-31 17:05:03.916 8119 9172 E SyncService: at android.text.format.Time.parse3339(Time.java:487)
12-31 17:05:03.916 8119 9172 E SyncService: at org.tomdroid.Note.getLastChangeDate(Note.java:184)
12-31 17:05:03.916 8119 9172 E SyncService: at org.tomdroid.sync.SyncService.prepareSyncableNotes(SyncService.java:330)
12-31 17:05:03.916 8119 9172 E SyncService: at org.tomdroid.sync.web.SnowySyncService.access$8(SnowySyncService.java:1)
12-31 17:05:03.916 8119 9172 E SyncService: at org.tomdroid.sync.web.SnowySyncService$3.run(SnowySyncService.java:263)
12-31 17:05:03.916 8119 9172 E SyncService: at org.tomdroid.sync.SyncService$1.run(SyncService.java:169)
12-31 17:05:03.916 8119 9172 E SyncService: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
12-31 17:05:03.916 8119 9172 E SyncService: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
12-31 17:05:03.916 8119 9172 E SyncService: at java.lang.Thread.run(Thread.java:856)

---

Imported from Launchpad using lp2gh.
- date created: 2013-01-05T18:08:55Z
- owner: plaxx
- the launchpad url was https://bugs.launchpad.net/bugs/1096420

**Comment by obilodeau** [comment]
(by j-4)
Hi! Which server do you use for syncing? did you use the latest build from here: http://goo.gl/fKg6N ?
I tried everything today, but couldn't reproduce your issue...

**Comment by obilodeau** [comment]
(by rsyring)
UbuntuOne.

Yes, I tried with that build.

**Comment by obilodeau** [comment]
(by j-4)
Hi! Can you check your note files on the computer and try to edit the *.note files manually to the right date format? I don't know how many notes you have - if it is too much, I could write a script for you! 
There might still be one or several corrupted notes in your database, which cause the troubles.

After editing, delete the notes on Tomdroid (clear local database), push them from the computer to ubuntu one and then pull them again to your mobile.

Sorry for the inconveniences!

**Comment by obilodeau** [comment]
(by rsyring)
Actually, I had some issues with UbuntuOne last month:

http://lists.beatniksoftware.com/pipermail/tomboy-list-beatniksoftware.com/2013-February/002861.html

whereby all my notes were getting deleted.  That must have fixed my issue because I can now sync successfully with Tomdroid.

**Comment by obilodeau** [comment]
(by j-4)
Great. If it comes back, please report a new bug. Until then I mark this as won't fix (as ubuntu one also shut down now, it won't fix anyway!)

Thanks for your great help!
