### ISSUE TITLE
Problem parsing the server response

### ISSUE THREAD

**Issue by obilodeau** [tomboy-notes/tomdroid#78]
Tomdroid Version 0.4.1
Android 2.2

When I set the server to sync with UbuntuOne, it redirect me to the web site to authenticate. 
I login, then I return to Tomdroid, push the sync button. 
There is no sync at all.
I removed and reinstalled Tomdroid twice with no more success.
With ddms I got those logs:

11-28 23:58:50.226: VERBOSE/SyncService(6181): sync progress: 0
11-28 23:58:50.236: WARN/System.err(6181): java.lang.IllegalStateException: Target host must not be null, or set in parameters.
11-28 23:58:50.236: WARN/System.err(6181):     at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:561)
11-28 23:58:50.236: WARN/System.err(6181):     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:292)
11-28 23:58:50.236: WARN/System.err(6181):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
11-28 23:58:50.236: WARN/System.err(6181):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
11-28 23:58:50.236: WARN/System.err(6181):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
11-28 23:58:50.236: WARN/System.err(6181):     at org.tomdroid.sync.web.WebConnection.execute(WebConnection.java:122)
11-28 23:58:50.246: WARN/System.err(6181):     at org.tomdroid.sync.web.OAuthConnection.get(OAuthConnection.java:239)
11-28 23:58:50.246: WARN/System.err(6181):     at org.tomdroid.sync.web.SnowySyncService$3.run(SnowySyncService.java:153)
11-28 23:58:50.246: WARN/System.err(6181):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1068)
11-28 23:58:50.246: WARN/System.err(6181):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:561)
11-28 23:58:50.246: WARN/System.err(6181):     at java.lang.Thread.run(Thread.java:1102)
11-28 23:58:50.246: VERBOSE/SyncService(6181): sync progress: 30
11-28 23:58:50.246: ERROR/SnowySyncService(6181): Problem parsing the server response
11-28 23:58:50.246: ERROR/SnowySyncService(6181): org.json.JSONException: End of input at character 0 of 
11-28 23:58:50.246: ERROR/SnowySyncService(6181):     at org.json.JSONTokener.syntaxError(JSONTokener.java:446)
11-28 23:58:50.246: ERROR/SnowySyncService(6181):     at org.json.JSONTokener.nextValue(JSONTokener.java:93)
11-28 23:58:50.246: ERROR/SnowySyncService(6181):     at org.json.JSONObject.<init>(JSONObject.java:154)
11-28 23:58:50.246: ERROR/SnowySyncService(6181):     at org.json.JSONObject.<init>(JSONObject.java:171)
11-28 23:58:50.246: ERROR/SnowySyncService(6181):     at org.tomdroid.sync.web.SnowySyncService$3.run(SnowySyncService.java:155)
11-28 23:58:50.246: ERROR/SnowySyncService(6181):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1068)
11-28 23:58:50.246: ERROR/SnowySyncService(6181):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:561)
11-28 23:58:50.246: ERROR/SnowySyncService(6181):     at java.lang.Thread.run(Thread.java:1102)
11-28 23:58:50.246: VERBOSE/SyncService(6181): sync progress: 100

---

Imported from Launchpad using lp2gh.
- date created: 2010-11-29T05:22:10Z
- owner: mario-bertrand
- assignee: plaxx
- the launchpad url was https://bugs.launchpad.net/bugs/682553

**Comment by obilodeau** [comment]
(by obilodeau)
Looking at "Target host must not be null, or set in parameters." can you confirm to me that you put: https://one.ubuntu.com/notes in the Server parameter?

We have done some work regarding error reporting with notes that we can't parse. If you are familiar with running development android applications please try the lp:tomdroid branch. Otherwise, stay tuned for our next release.

**Comment by obilodeau** [comment]
(by mario-bertrand)
Yes, I did put the https://one.ubuntu.com/notes in the server parameter.
The problem is fixed now, I found that it was using fennec beta that
caused the problem (as with many other sites). When using the default
browser, the login is ok.

Thanks.

## 

Mario Bertrand

**Comment by obilodeau** [comment]
(by obilodeau)
As Mario reported, this was caused by Fennec beta. Marking as invalid.
