### ISSUE TITLE
crash on exit

### ISSUE THREAD

**Issue by obilodeau** [tomboy-notes/tomdroid#79]
Reported on the Android Market for Tomdroid 0.4.1.

User comment:
it just crashed on exit

Stack trace:
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@43cccb20 is not valid; is your activity running?
at android.view.ViewRoot.setView(ViewRoot.java:505)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:177)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
at android.view.Window$LocalWindowManager.addView(Window.java:424)
at android.app.Dialog.show(Dialog.java:241)
at android.app.AlertDialog$Builder.show(AlertDialog.java:802)
at org.tomdroid.ui.SyncMessageHandler.handleMessage(SyncMessageHandler.java:94)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)

---

Imported from Launchpad using lp2gh.
- date created: 2010-12-12T22:44:58Z
- owner: plaxx
- the launchpad url was https://bugs.launchpad.net/bugs/689441

**Comment by obilodeau** [comment]
(by j-4)
I also managed to crash it with the same log entries today... I did authentification quite often and then during sync I pressed menu -> settings and it crashed... 
I assume this is some error when interrupting syncing with the settings dialog respectively quitting the app.

**Comment by obilodeau** [comment]
(by obilodeau)
thanks for making it reproducible!

**Comment by obilodeau** [comment]
(by j-4)
can't reproduce any more. will close this one!
