### ISSUE TITLE
NullPointer in SD Card Sync

### ISSUE THREAD

**Issue by obilodeau** [tomboy-notes/tomdroid#80]
A lot of reports in the Android Market on this one.

User comments:
- refreshing with no account details
- tomdroid crashes when sync button is pushed after setting tomdroid to sync with SD card on phone
- Crashed on attempt to sync.
- crashed during the initial sync, again.
- trying to run an initial sync with https://one.Ubuntu.com/notes
- Tomdroid crashes on sync. Using Dropbox as sync folder in Droid2
- craché a la synchronisation
- gerade installiert
- application crashes every time I press the synch icon to synch with the SD card
- just go drown
- Just installed the app and it crashed when I pressed the sync button
- Doesn't sync.....just shows force close prompt

Stack trace:
java.lang.NullPointerException
at org.tomdroid.sync.sd.SdCardSyncService.sync(SdCardSyncService.java:103)
at org.tomdroid.sync.SyncService.startSynchronization(SyncService.java:75)
at org.tomdroid.sync.SyncManager.startSynchronization(SyncManager.java:64)
at org.tomdroid.ui.Actionbar$1.onClick(Actionbar.java:64)
at android.view.View.performClick(View.java:2408)
at android.view.View$PerformClick.run(View.java:8817)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:144)
at android.app.ActivityThread.main(ActivityThread.java:4937)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)

FYI The stack traces are not all the same but hey are very very similar, I would have to diff them to view a difference.

I am able to reproduce something similar on my new samsung galaxy s. I think the way they handle the internal memory vs external sdcard has something to do with this. Without a real micro-sd you still have a /sdcard/ folder and you probably need special permissions to read there (as opposed to a real external micro-sd).

---

Imported from Launchpad using lp2gh.
- date created: 2010-12-12T22:51:39Z
- owner: plaxx
- assignee: plaxx
- the launchpad url was https://bugs.launchpad.net/bugs/689443

**Comment by obilodeau** [comment]
(by benoit.garret)
I'll try to reproduce this, one of my coworkers has a galaxy s I can borrow. Are all these crashes related to the SD card (I'm seeing reports related to ubuntu one syncing)?

**Comment by obilodeau** [comment]
(by obilodeau)
Users commented about the fact that they were trying Ubuntu One sync but all the stack traces were related to NullPointers in org.tomdroid.sync.sd.SdCardSyncService so I'm not sure what to think of that.

**Comment by obilodeau** [comment]
(by j-4)
Could the reason for this bug be that in  tomboy 0.4.1 there was no  
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
included in the manifest? Maybe some manufacturers proved the permissions better, than others.
This would be fixed now in 5.0, so maybe the bug is already gone.

**Comment by obilodeau** [comment]
(by j-4)
Hi there!

I could just test my assumption from post #3 on a Samsung Nexus S with internal "SD Card" storage.

When using Tomdroid 4.1 from the Market I get a force quit with the NullPointerException when importing the notes from the "sdcard". Log is attached!

On the same device, same notes but using Tomdroid 5.1 (main branch) this doesn't happen.

Therefore it seems this bug is fixed already. Probably through adding of the "android.permission.WRITE_EXTERNAL_STORAGE" line. So it will be in the next release.

Can I close this bug?

**Comment by obilodeau** [comment]
(by obilodeau)
Based on Stefan's comment, this was fixed in released 0.5.0. Marking as such.
