### ISSUE TITLE
Tomdroid crashes when pressing cancel on UbuntuOne page during Authentification

### ISSUE THREAD

**Issue by obilodeau** [tomboy-notes/tomdroid#86]
04-01 10:27:53.296: V/FirstNote(10330): Creating first note
04-01 10:27:53.306: V/NoteManager(10330): A new note has been detected (not yet in db)
04-01 10:27:53.346: V/NoteManager(10330): Note inserted in content provider. ID: content://org.tomdroid.notes/notes/1 TITLE:Tomdroid's first note GUID:8f837a99-c920-4501-b303-6a39af57a714
04-01 10:28:03.746: I/Tomdroid(10330): Got url : tomdroid://sync?return=https://one.ubuntu.com
04-01 10:28:03.766: I/OAuthConnection(10330): Verifier: null
04-01 10:28:03.766: D/OAuthConnection(10330): Added request token 6w8qJkD5gRMpfn4twf6q and request token secret r1M3J3hJNdqTT1jVFFgg9wDlKbZpbD3pfnBrtMzFt6c8rW1s4hHH5rkwGPqpTgfL8Hhs37m48kffpd5r
04-01 10:28:04.116: D/dalvikvm(10330): GC_CONCURRENT freed 1250K, 49% free 3942K/7623K, external 2950K/3361K, paused 2ms+4ms
04-01 10:28:04.356: E/SnowySyncService(10330): Unidentified authentication error. Expception: oauth.signpost.exception.OAuthCommunicationException Message: Communication with the service provider failed: Service provider responded in error: 400 (BAD REQUEST)
04-01 10:28:04.356: W/System.err(10330): oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: Service provider responded in error: 400 (BAD REQUEST)
04-01 10:28:04.356: W/System.err(10330):    at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:218)
04-01 10:28:04.356: W/System.err(10330):    at oauth.signpost.AbstractOAuthProvider.retrieveAccessToken(AbstractOAuthProvider.java:108)
04-01 10:28:04.356: W/System.err(10330):    at org.tomdroid.sync.web.OAuthConnection.getAccess(OAuthConnection.java:185)
04-01 10:28:04.356: W/System.err(10330):    at org.tomdroid.sync.web.SnowySyncService$2.run(SnowySyncService.java:125)
04-01 10:28:04.366: W/System.err(10330):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
04-01 10:28:04.366: W/System.err(10330):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
04-01 10:28:04.366: W/System.err(10330):    at java.lang.Thread.run(Thread.java:1019)
04-01 10:28:04.366: W/System.err(10330): Caused by: oauth.signpost.exception.OAuthCommunicationException: Service provider responded in error: 400 (BAD REQUEST)
04-01 10:28:04.376: W/System.err(10330):    at oauth.signpost.AbstractOAuthProvider.handleUnexpectedResponse(AbstractOAuthProvider.java:245)
04-01 10:28:04.376: W/System.err(10330):    at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:193)
04-01 10:28:04.376: W/System.err(10330):    ... 6 more
04-01 10:28:04.396: D/AndroidRuntime(10330): Shutting down VM
04-01 10:28:04.396: W/dalvikvm(10330): threadid=1: thread exiting with uncaught exception (group=0x40015560)
04-01 10:28:04.396: E/AndroidRuntime(10330): FATAL EXCEPTION: main
04-01 10:28:04.396: E/AndroidRuntime(10330): android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@40704650 is not valid; is your activity running?
04-01 10:28:04.396: E/AndroidRuntime(10330):    at android.view.ViewRoot.setView(ViewRoot.java:527)
04-01 10:28:04.396: E/AndroidRuntime(10330):    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:177)
04-01 10:28:04.396: E/AndroidRuntime(10330):    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
04-01 10:28:04.396: E/AndroidRuntime(10330):    at android.view.Window$LocalWindowManager.addView(Window.java:424)
04-01 10:28:04.396: E/AndroidRuntime(10330):    at android.app.Dialog.show(Dialog.java:241)
04-01 10:28:04.396: E/AndroidRuntime(10330):    at android.app.AlertDialog$Builder.show(AlertDialog.java:802)
04-01 10:28:04.396: E/AndroidRuntime(10330):    at org.tomdroid.ui.SyncMessageHandler.handleMessage(SyncMessageHandler.java:112)
04-01 10:28:04.396: E/AndroidRuntime(10330):    at android.os.Handler.dispatchMessage(Handler.java:99)
04-01 10:28:04.396: E/AndroidRuntime(10330):    at android.os.Looper.loop(Looper.java:130)
04-01 10:28:04.396: E/AndroidRuntime(10330):    at android.app.ActivityThread.main(ActivityThread.java:3683)
04-01 10:28:04.396: E/AndroidRuntime(10330):    at java.lang.reflect.Method.invokeNative(Native Method)
04-01 10:28:04.396: E/AndroidRuntime(10330):    at java.lang.reflect.Method.invoke(Method.java:507)
04-01 10:28:04.396: E/AndroidRuntime(10330):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
04-01 10:28:04.396: E/AndroidRuntime(10330):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
04-01 10:28:04.396: E/AndroidRuntime(10330):    at dalvik.system.NativeStart.main(Native Method)
04-01 10:28:05.628: I/Process(10330): Sending signal. PID: 10330 SIG: 9

---

Imported from Launchpad using lp2gh.
- date created: 2012-04-01T08:31:26Z
- owner: j-4
- the launchpad url was https://bugs.launchpad.net/bugs/970657

**Comment by obilodeau** [comment]
(by j-4)
Another time I get other messages... this time a NullPointer (at android 1.6, before was 2.3)

04-01 08:39:13.157: E/SnowySyncService(285): Unidentified authentication error. Expception: oauth.signpost.exception.OAuthCommunicationException Message: Communication with the service provider failed: Service provider responded in error: 400 (BAD REQUEST)
04-01 08:39:13.167: W/System.err(285): oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: Service provider responded in error: 400 (BAD REQUEST)
04-01 08:39:13.167: W/System.err(285):  at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:218)
04-01 08:39:13.167: W/System.err(285):  at oauth.signpost.AbstractOAuthProvider.retrieveAccessToken(AbstractOAuthProvider.java:108)
04-01 08:39:13.167: W/System.err(285):  at org.tomdroid.sync.web.OAuthConnection.getAccess(OAuthConnection.java:185)
04-01 08:39:13.167: W/System.err(285):  at org.tomdroid.sync.web.SnowySyncService$2.run(SnowySyncService.java:125)
04-01 08:39:13.167: W/System.err(285):  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:648)
04-01 08:39:13.167: W/System.err(285):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:673)
04-01 08:39:13.167: W/System.err(285):  at java.lang.Thread.run(Thread.java:1060)
04-01 08:39:13.167: W/System.err(285): Caused by: oauth.signpost.exception.OAuthCommunicationException: Service provider responded in error: 400 (BAD REQUEST)
04-01 08:39:13.167: W/System.err(285):  at oauth.signpost.AbstractOAuthProvider.handleUnexpectedResponse(AbstractOAuthProvider.java:245)
04-01 08:39:13.167: W/System.err(285):  at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:193)
04-01 08:39:13.177: W/System.err(285):  ... 6 more
04-01 08:39:13.177: W/dalvikvm(285): threadid=17: thread exiting with uncaught exception (group=0x4001aa28)
04-01 08:39:13.177: E/AndroidRuntime(285): Uncaught handler: thread pool-1-thread-1 exiting due to uncaught exception
04-01 08:39:13.177: E/AndroidRuntime(285): java.lang.NullPointerException
04-01 08:39:13.177: E/AndroidRuntime(285):  at org.tomdroid.sync.SyncService.sendException(SyncService.java:218)
04-01 08:39:13.177: E/AndroidRuntime(285):  at org.tomdroid.sync.web.SnowySyncService.access$1(SnowySyncService.java:1)
04-01 08:39:13.177: E/AndroidRuntime(285):  at org.tomdroid.sync.web.SnowySyncService$2.run(SnowySyncService.java:138)
04-01 08:39:13.177: E/AndroidRuntime(285):  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:648)
04-01 08:39:13.177: E/AndroidRuntime(285):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:673)
04-01 08:39:13.177: E/AndroidRuntime(285):  at java.lang.Thread.run(Thread.java:1060)
04-01 08:39:13.187: I/dalvikvm(285): threadid=7: reacting to signal 3
04-01 08:39:13.187: E/dalvikvm(285): Unable to open stack trace file '/data/anr/traces.txt': Permission denied
04-01 08:39:16.476: I/global(285): Default buffer size used in BufferedReader constructor. It would be better to be explicit if an 8k-char buffer is required.
04-01 08:39:16.476: E/SnowySyncService(285): Unidentified authentication error. Expception: oauth.signpost.exception.OAuthCommunicationException Message: Communication with the service provider failed: Service provider responded in error: 400 (BAD REQUEST)
04-01 08:39:16.476: W/System.err(285): oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: Service provider responded in error: 400 (BAD REQUEST)
04-01 08:39:16.476: W/System.err(285):  at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:218)
04-01 08:39:16.476: W/System.err(285):  at oauth.signpost.AbstractOAuthProvider.retrieveAccessToken(AbstractOAuthProvider.java:108)
04-01 08:39:16.476: W/System.err(285):  at org.tomdroid.sync.web.OAuthConnection.getAccess(OAuthConnection.java:185)
04-01 08:39:16.476: W/System.err(285):  at org.tomdroid.sync.web.SnowySyncService$2.run(SnowySyncService.java:125)
04-01 08:39:16.476: W/System.err(285):  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:648)
04-01 08:39:16.487: W/System.err(285):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:673)
04-01 08:39:16.487: W/System.err(285):  at java.lang.Thread.run(Thread.java:1060)
04-01 08:39:16.487: W/System.err(285): Caused by: oauth.signpost.exception.OAuthCommunicationException: Service provider responded in error: 400 (BAD REQUEST)
04-01 08:39:16.487: W/System.err(285):  at oauth.signpost.AbstractOAuthProvider.handleUnexpectedResponse(AbstractOAuthProvider.java:245)
04-01 08:39:16.487: W/System.err(285):  at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:193)
04-01 08:39:16.487: W/System.err(285):  ... 6 more

**Comment by obilodeau** [comment]
(by obilodeau)
another thing to look at. Would you call this a blocker for the next release?

**Comment by obilodeau** [comment]
(by j-4)
Maybe yes.... unfortunately. A crash shouldn't persist after we found it.

**Comment by obilodeau** [comment]
(by j-4)
Great... now as I wanted to fix it, I can't reproduce it any more... 
If you also can't reproduce it we should just leave it as it is and remove it from the 0.5.1 milestone. Maybe it was just bad luck two times :-)

**Comment by obilodeau** [comment]
(by j-4)
This crash still happens on latest beta!

changing sync service in Tomdroid, clicked sync -> ubuntu one homepage comes, click cancel button -> crash
Afterwards on restarting Tomdroid -> again crash. Next start then worked.

here is the log: http://pastebin.com/hN6AePP7 (there is also a lot of mozilla logging in between :-S )

I will also try it on a virtual machine with a fresh install.

**Comment by obilodeau** [comment]
(by noahy)
This is the same bug as lp:1040581; both should be fixed in the latest revision - please confirm :)

**Comment by obilodeau** [comment]
(by j-4)
yes, this is also fixed on my device. I hope there are no more crashes! Thank you very much.
